###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################
based_on_package: "crx_mock"

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware by changing a single parameter with config inheritance.
  # [Required]
  simulated: false
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      # If you'd like to use a different CRX model, enter in the crx_mock (but you can also enter it here using the `robot_model` param).
      - robot_ip: "192.168.1.100"
      - rmi_port: "16001"
      - stream_motion_port: "60015"
      - gpio_configuration: "$(find crx_hw)/config/control/gpio_config.yaml"
      - use_mock: "false"

# Sets ROS global params for launch.
# [Optional]
ros_global_params:
  # Whether or not to use simulated time.
  # [Optional, default=False]
  use_sim_time: False

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "crx_hw"
    path: "config/control/ros2_control.yaml"
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "joint_trajectory_controller"
    - "fanuc_gpio_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    - "velocity_force_controller"
    - "servo_controller"
# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    mock_objectives:
      package_name: "crx_mock"
      relative_path: "objectives"
    hw_objectives:
      package_name: "crx_hw"
      relative_path: "objectives"
